# Generated by Django 5.1.1 on 2024-10-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
